### ISSUE TITLE
Spacing on popup

### ISSUE THREAD

**Issue by Oliversw** [fack2/ptfb-griffinot#181]
![Screen Shot 2019-10-30 at 10 13 36 AM](https://user-images.githubusercontent.com/9094166/67849372-65ea4580-fafe-11e9-9408-064e6415e7cf.png)

There's a minor issue with the logo size (see #180), but also there are some issues with the spacing of text on the questionnaire popups

**Comment by hshahwan** [comment]
@sara219  is working on it now.
all popups will update now.
