### ISSUE TITLE
Spacing on questionnaire on desktop

### ISSUE THREAD

**Issue by Oliversw** [fack2/ptfb-griffinot#182]
![Screen Shot 2019-10-30 at 10 18 44 AM](https://user-images.githubusercontent.com/9094166/67849570-b19cef00-fafe-11e9-9b43-dc25f9c6423a.png)

It's a little off to one side

**Comment by hshahwan** [comment]
@Oliversw 
check it now

**Comment by Oliversw** [comment]
Also when there is less width the text is too big, so might need a media query to reduce the `rem`
![Screen Shot 2019-10-30 at 10 20 11 AM](https://user-images.githubusercontent.com/9094166/67849806-16f0e000-faff-11e9-9d42-ab6767755b77.png)

**Comment by hshahwan** [comment]
@Oliversw 
https://ptfb-griffinot.herokuapp.com/
next and prev button also it will be done at the end of the day
