### ISSUE TITLE
Text too large on Firefox mobile view

### ISSUE THREAD

**Issue by Oliversw** [fack2/ptfb-griffinot#184]
It's strange but on my browser when I go to phone view, nothing works, but on my mobile phone it looks almost perfect I'm not sure how that is happening. How are you developing the app? Are you using chrome or firefox with mobile view on dev tools?

![Screen Shot 2019-10-30 at 10 23 13 AM](https://user-images.githubusercontent.com/9094166/67849938-57e8f480-faff-11e9-93a6-39552ba429ce.png)

**Comment by hshahwan** [comment]
fixed now
