### ISSUE TITLE
Some text overflows and next button is off to the side in questionnaire

### ISSUE THREAD

**Issue by Oliversw** [fack2/ptfb-griffinot#186]
Amazing changes for the mobile view!! Just a couple of other very small things now
![Screen Shot 2019-10-30 at 10 26 58 AM](https://user-images.githubusercontent.com/9094166/67850296-0c831600-fb00-11e9-9061-3b2b2d3fefd5.png)
![Screen Shot 2019-10-30 at 10 28 02 AM](https://user-images.githubusercontent.com/9094166/67850299-0db44300-fb00-11e9-946a-7384492f0ca5.png)

**Comment by hshahwan** [comment]
@SajaLahaleeh  need to add a media query 
```
@media (max-width: 480px)
``` 
and work on font size and width
