### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by 95Rawan** [fack2/ptfb-griffinot#25]
* Contents:
- Section one:
  - [x]  Blue background with a kid holding a kite logo
- Section two:
  - [x] White background that changes content depending on where we use it.

- [x] PropTypes validator 

![image](https://user-images.githubusercontent.com/47659847/66288305-59991100-e8e1-11e9-9a5a-3d37e1e98fd4.png)

**Comment by Oliversw** [comment]
Maybe it could take a color value as a prop?
