### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by 95Rawan** [fack2/ptfb-griffinot#32]
* Contents:
- [x] Header Component #24 
- [x] Title 
- [x] Some text
- [x] Diagram picture
- [x] Start text and arrow icon #26 

![image](https://user-images.githubusercontent.com/47659847/66290994-5013a700-e8e9-11e9-85e0-0c6481d2d7a9.png)

**Comment by sara219** [comment]
The button still doesn't work _( pop-up question doesn't show after clicking on the start button)_
