### ISSUE TITLE
File Structure 

### ISSUE THREAD

**Issue by sara219** [fack2/ptfb-griffinot#49]
- public
  - index.js
- src
  - Date
    - data.json
  - CommonComponents
     - Header
        - index.js
        - index.style.js
        - menu.js
     - Question
        - index.js
        - index.style.js
     - Level
        - index.js
        - index.style.js
     - Pop
       - index.js
       - index.style.js
    - NextPre
       - index.js
       - index.style.js
    - Resource
      - index.js
      - index.style.js
```
```

**Comment by sara219** [comment]
- src
  - Layouts
    - LandingPage
        - index.js
        - index.style.js
    - Schem
       - index.js
       - index.style.js
    - Questionnaire
       - SectionA.js
       - SectionB.js
       - SectionC.js
       - SectionD1.js
       - SectionD2.js
       - index.js
       - index.style.js
       - Option3
    - Resources
       - index.js
       - index.style.css
    - Video 
        - index.js
        - index.style.js
    - Book
       - index.js
       - index.style.js
    - Blog
      - index.js
      - index.style.js
    - AboutUs
      - index.js
      - index.style.js
    - Level
       - index.js
       - index.style.js

**Comment by hshahwan** [comment]
@sara219 Don't forget to add Data folder

**Comment by sara219** [comment]
@hshahwan  I added it!
